name: 🧪 Continuous integration
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🐧 Linux (x64)
            os: ubuntu-22.04
            rid: linux-x64
            cibuild-script: ./eng/common/cibuild.sh --warnaserror false

          - name: 🏁 Windows (x64)
            os: windows-latest
            rid: win-x64
            cibuild-script: ./eng/common/CIBuild.cmd -warnAsError 0

          - name: 🍎 macOS (x64)
            os: macos-latest
            rid: osx-arm64
            cibuild-script: ./eng/common/cibuild.sh --warnaserror false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Linux dependencies
        if: ${{ matrix.rid == 'linux-x64' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config

      # Setting up .NET with the GitHub action to register the
      # problem matchers for error output.
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build and test solution
        run: |
          ${{ matrix.cibuild-script }} --integrationTest /p:GenerateGodotBindings=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-dotnet-${{ matrix.rid }}-artifacts
          path: artifacts/
          if-no-files-found: error
